- name: Test if docker is installed
  command: docker
  register: result
  ignore_errors: true
- name: Install Docker
  apt:
    name: docker.io
    update_cache: yes
    state: latest
  when: result is failed
  become: true
- name: Add ubuntu to docker group
  shell: usermod -aG docker ubuntu
  become: true
  when: result is failed
- name: Start Docker service
  shell: service docker start
  become: true